Feature/user matching workflow
CS3219-AY2425S1/cs3219-ay2425s1-project-g08 pull request #52
Opened 2024-10-19 12:41 UTC by Pughal77

User is now able to connect to a websocket with another user.

The request to connect to a websocket times out after 30s.

User is also able to broadcast a message to all clients that are connected to a websocket

2024-10-19 15:13 UTC, DonovanJJ requested changes
Thanks for working on the frontend code! The UI looks great 👍 
However, note that you will need to add back the function that was accidentally deleted during merge

2024-10-19 15:13 UTC, DonovanJJ commented on frontend/src/components/ProfileButton.tsx
> +  useEffect(() => {
Could we merge these two `useEffect` together since they are both dependent on `currUser`?

2024-10-19 15:13 UTC, DonovanJJ commented on matchingService/src/QueueService/Consumer.ts
> -    private startPendingReqTimeout(req: MatchRequestDTO): void {
**Important**: Breaking change made here. `startPendingReqTimeout` should not be deleted!

2024-10-19 15:13 UTC, DonovanJJ commented on matchingService/src/QueueService/Consumer.ts
I think our linter is different so theres quite a bit of changes here with regards to coding style.
Could you help to look through and make sure no other logic change was done in the matching service aside from the `startPendingReqTimeout` / revert the indentations to make it easier to review
I've tired my best to double check things but I may have missed things out

2024-10-20 02:47 UTC, Pughal77 commented on matchingService/src/QueueService/Consumer.ts
Ok sure. I will disable my linting for now to prevent future errors. I will check on my end as well

2024-10-20 02:54 UTC, merged